name: Feature Request
description: Suggest a new feature or enhancement for boom-ui
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the information below to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: Why is this feature needed? What problem does it solve?
      placeholder: This feature would help...
    validations:
      required: true

  - type: textarea
    id: proposed-api
    attributes:
      label: Proposed API / Implementation
      description: If you have ideas about how this should work, share them here.
      placeholder: |
        ```tsx
        <Component prop="value">
          Content
        </Component>
        ```
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What needs to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false
